import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Background Elements */}
        <div className="main-bg" />
        <div className="grid-pattern" />
        <div className="noise-bg" />
        <div className="background-glow">
          <div className="glow-circle glow-circle-1" />
          <div className="glow-circle glow-circle-2" />
          <div className="glow-circle glow-circle-3" />
        </div>
        <div className="gradient-dots" />

        {/* Navigation */}
        <nav className="fixed top-0 w-full border-b border-border/40 backdrop-blur-md supports-[backdrop-filter]:bg-background/60 z-50">
          <div className="container h-16 flex items-center justify-between">
            <div className="flex items-center gap-6">
              <a href="/" className="flex items-center gap-2">
                <span className="text-xl font-bold text-gradient">Acapella</span>
              </a>
              <div className="hidden md:flex items-center gap-6">
                <a href="/docs" className="nav-link">Документация</a>
                <a href="/community" className="nav-link">Сообщество</a>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <button className="button button-primary" href="https://627cbeb2206798.lhr.life/">Начать</button>
            </div>
          </div>
        </nav>

        {/* Main Content */}
        <main className="pt-24 relative">
          {children}
        </main>
      </body>
    </html>
  );
}
